using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using OnLocationGallagherBridge.Models;
using Serilog;

namespace OnLocationGallagherBridge.Services;

public static class CertificateLoader
{
    public static X509Certificate2? Load(HttpsConfig config, string dataDir, ConfigService configService, Serilog.ILogger logger)
    {
        try
        {
            return config.CertificateSource?.ToLowerInvariant() switch
            {
                "thumbprint" => LoadFromThumbprint(config.CertificateThumbprint, logger),
                "pfx" => LoadFromPfx(config.CertificatePath, config.CertificatePassword, dataDir, logger),
                _ => LoadAutoGenerated(dataDir, config, configService, logger)
            };
        }
        catch (Exception ex)
        {
            logger.Error(ex, "Failed to load HTTPS certificate");
            return null;
        }
    }

    private static X509Certificate2? LoadFromThumbprint(string? thumbprint, Serilog.ILogger logger)
    {
        if (string.IsNullOrWhiteSpace(thumbprint))
        {
            logger.Error("HTTPS certificate thumbprint is not configured");
            return null;
        }

        var cleaned = thumbprint.Replace(" ", string.Empty).Replace(":", string.Empty).ToUpperInvariant();
        foreach (var location in new[] { StoreLocation.LocalMachine, StoreLocation.CurrentUser })
        {
            using var store = new X509Store(StoreName.My, location);
            store.Open(OpenFlags.ReadOnly);
            var cert = store.Certificates
                .FirstOrDefault(c =>
                    c.Thumbprint?.Equals(cleaned, StringComparison.OrdinalIgnoreCase) == true);
            if (cert is not null)
            {
                logger.Information("Loaded HTTPS certificate {Thumbprint} from {Store}", cert.Thumbprint, location);
                return X509CertificateLoader.LoadCertificate(cert.Export(X509ContentType.Pfx));
            }
        }

        logger.Error("HTTPS certificate with thumbprint {Thumbprint} was not found in the machine or user certificate store", thumbprint);
        return null;
    }

    private static X509Certificate2? LoadFromPfx(string? path, string? password, string dataDir, Serilog.ILogger logger)
    {
        if (string.IsNullOrWhiteSpace(path))
        {
            logger.Error("HTTPS certificate path is not configured");
            return null;
        }

        var resolvedPath = Path.IsPathRooted(path) ? path : Path.Combine(dataDir, path);
        if (!File.Exists(resolvedPath))
        {
            logger.Error("HTTPS certificate file not found at {Path}", resolvedPath);
            return null;
        }

        var cert = string.IsNullOrWhiteSpace(password)
            ? X509CertificateLoader.LoadPkcs12FromFile(resolvedPath, ReadOnlySpan<char>.Empty, X509KeyStorageFlags.Exportable | X509KeyStorageFlags.PersistKeySet)
            : X509CertificateLoader.LoadPkcs12FromFile(resolvedPath, password.AsSpan(), X509KeyStorageFlags.Exportable | X509KeyStorageFlags.PersistKeySet);

        if (!cert.HasPrivateKey)
        {
            logger.Error("HTTPS certificate at {Path} does not contain a private key", resolvedPath);
            return null;
        }

        logger.Information("Loaded HTTPS certificate from {Path}", resolvedPath);
        return cert;
    }

    private static X509Certificate2 LoadAutoGenerated(string dataDir, HttpsConfig config, ConfigService configService, Serilog.ILogger logger)
    {
        var certPath = Path.Combine(dataDir, "bridge-https.pfx");
        if (File.Exists(certPath))
        {
            var password = config.CertificatePassword;
            if (string.IsNullOrWhiteSpace(password))
            {
                logger.Error("Auto-generated HTTPS certificate exists but the password is not set in configuration");
                throw new InvalidOperationException("Auto-generated certificate password is missing");
            }

            var cert = X509CertificateLoader.LoadPkcs12FromFile(certPath, password.AsSpan(), X509KeyStorageFlags.Exportable | X509KeyStorageFlags.PersistKeySet);
            logger.Information("Loaded auto-generated HTTPS certificate from {Path}", certPath);
            return cert;
        }

        logger.Information("Generating a new self-signed HTTPS certificate");

        var sanBuilder = new SubjectAlternativeNameBuilder();
        sanBuilder.AddDnsName("localhost");
        try
        {
            var hostName = Environment.MachineName;
            if (!string.Equals(hostName, "localhost", StringComparison.OrdinalIgnoreCase))
                sanBuilder.AddDnsName(hostName);
        }
        catch { /* best effort */ }
        sanBuilder.AddIpAddress(System.Net.IPAddress.Loopback);

        using var rsa = RSA.Create(2048);
        var request = new CertificateRequest(
            new X500DistinguishedName("CN=OnLocation-Gallagher-Bridge"),
            rsa,
            HashAlgorithmName.SHA256,
            RSASignaturePadding.Pkcs1);
        request.CertificateExtensions.Add(sanBuilder.Build());
        request.CertificateExtensions.Add(new X509BasicConstraintsExtension(false, false, 0, false));
        request.CertificateExtensions.Add(new X509KeyUsageExtension(X509KeyUsageFlags.DigitalSignature | X509KeyUsageFlags.KeyEncipherment, false));

        var certificate = request.CreateSelfSigned(
            DateTimeOffset.UtcNow.AddDays(-1),
            DateTimeOffset.UtcNow.AddYears(5));

        var pfxPassword = Convert.ToBase64String(RandomNumberGenerator.GetBytes(24));
        var pfxBytes = certificate.Export(X509ContentType.Pfx, pfxPassword);
        Directory.CreateDirectory(dataDir);
        File.WriteAllBytes(certPath, pfxBytes);

        config.CertificatePath = certPath;
        config.CertificatePassword = pfxPassword;
        configService.SaveAsync().GetAwaiter().GetResult();

        logger.Information("Saved auto-generated HTTPS certificate to {Path}", certPath);

        return X509CertificateLoader.LoadPkcs12(pfxBytes, pfxPassword.AsSpan(), X509KeyStorageFlags.Exportable | X509KeyStorageFlags.PersistKeySet);
    }
}
